name: "Create Discord Embed"
description: "creates the json-representation of a custom discord embed, used in my workflows"

author: tristankechlo
branding:
  icon: "box"
  color: "blue"

inputs:
# required fields
  released:
    required: true
    description: "if the mod files were published to curseforge and modrinth"
    default: "true"
  changelog:
    required: true
    description: "the changelog of this update"
  version:
    required: true
    description: "the version of this update"
  color:
    required: true
    description: "the color of the discord embed"
  title:
    required: true
    description: "title of the embed"
  description:
    required: true
    description: "subtitle of the embed"
  curseforge:
    required: true
    description: "link to the curseforge page of the project"
  modrinth:
    required: true
    description: "link to the modrinth page of the project"
  github:
    required: true
    description: "link to the github repo"
  thumbnail:
    required: true
    description: "small thumbnail in the upper right corner of the embed"
# optional fields
  content:
    required: false
    description: "the message content above the embed"
    default: ""
  filename:
    required: true
    description: "the name of the file where the cull embed content will be saved"
    default: "embed.json"
  curseforge-emoji:
    required: false
    description: "emoji to use as the curseforge logo"
    default: "<:curseforge:938093919848267807>"
  modrinth-emoji:
    required: false
    description: "emoji to use as the modrinth logo"
    default: "<:modrinth:977251171980963890>"
  github-emoji:
    required: false
    description: "emoji to use as the github logo"
    default: "<:github:938091396785639434>"
  username:
    required: false
    description: "username of the webhook"
    default: "TK's Mod Releases"
  avatar-url:
    required: false
    description: "url to the image, that is used as the avatar of the webhook"
    default: "https://cdn.modrinth.com/data/UKDLi1GJ/d345468b19bfd5ffffa1ed070297a6a74535e9d6.png"
  changelog-split:
    required: false
    description: "if set, the provided changelog will be split at this position, only the first match will be used"
    default: "**Full Changelog**"

runs:
  using: node20
  main: dist/index.js
